### ISSUE TITLE
Oh the Biomes You'll Go Refabricated not cleared

### ISSUE THREAD

**Issue by AutoRunFail** [spoorn/StarterItems#1]
[Oh the Biomes You'll Go Refabricated](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) recently added a biomepedia to their mod. The button in the inventory for the book can be turned off in a config, but the mod always gives the book to the player on login and currently StarterItems does not clear it out even with the clearInventory set to true in the config. 
I am not using the Forge version of BYG, but I imagine the same is true with that version as well. 

~~StarterItems version: starterkit-fabric_1.19.x-3.1~~
Minecraft version: 1.18.2 on Fabric
Fabric API: 0.55.1 (though I have also tried it on 0.48.0, 0.51.1, 0.53.3 and 0.53.4)
Oh the Biomes You'll Go version:  Any version from 1.18.2-1.4-RC-12 through 1.18.2-1.4.1 ( I have not tested any of the 1.19 versions)

**Comment by spoorn** [comment]
Yes this is a known issue.  It's because StarterItems attempts to clear out the inventory when a player logs in, and it already has logic to try to do this after every mod, but some mods use other mechanisms to add items to the player - such as through an achievement or other - so it's not so easy to make sure StarterItems clearInventory is **always** called **AFTER** other mods' logic.  It has to be done in a more ad-hoc way

I'll have to look into this and see if I can figure out how to make sure clearInventory is triggered after whatever BYG did

Though, I noticed you linked the wrong mod:

```
StarterItems version: starterkit-fabric_1.19.x-3.1
```

Did you mean to put this in the starterkit Issues page, or were you having this problem with StarterItems?

**Comment by spoorn** [comment]
Fixed in 1.5.5-1.18.2+ and 2.0.1-1.19+

**Comment by AutoRunFail** [comment]
> Though, I noticed you linked the wrong mod:
> 
> ```
> StarterItems version: starterkit-fabric_1.19.x-3.1
> ```
> 
> Did you mean to put this in the starterkit Issues page, or were you having this problem with StarterItems?

My apologies! I was testing both mods and was looking at the wrong page when I posted. I meant to post 
StarterItems version:  starteritems-1.5.4

(edited original post to strikethrough incorrect mod for any future searches)

Thank you so much for the quick reply and update!  I downloaded the new file for 18.2 and tested it this morning and it works perfectly. Thank you again!
